Add PT-BR translation
openSUSE/news-o-o pull request #123
Opened 2022-06-09 03:58 UTC by vinyanalista

2022-06-17 09:16 UTC, lkocman commented
Hello @vinyanalista,

I think I know why the SR was not merged, your link is the only one outside of opensuse.org. Could you perhaps add translated text to our wiki page and reference this one?

Thank you for your understanding.

Lubos

2022-06-17 09:18 UTC, lkocman requested changes

2022-06-17 09:18 UTC, lkocman commented on _posts/2022-06-08-leap-offers-new-features-familiar-stability.md
> +[CA](https://en.opensuse.org/Anunci_de_la_versi%C3%B3_15.4) / [CS](http://cs.opensuse.org/Ozn%C3%A1men%C3%AD_nov%C3%A9ho_vyd%C3%A1n%C3%AD_15.4) / [ES](http://es.opensuse.org/Anuncio_publicaci%C3%B3n_
please use references to *.opensuse.org. See what we have https://pt.opensuse.org/P%C3%A1gina_Principal for portugese.

2022-06-19 08:34 UTC, ddemaio commented
added pt-br translation on https://github.com/openSUSE/news-o-o/commit/67e671996135459f8942656462b7b93b6eb83722

2022-06-19 08:34 UTC, closed without merging